# This file was generated by GoReleaser. DO NOT EDIT.
cask "pj" do
  name "pj"
  desc "Manage parallel projects backed by git worktrees"
  homepage "https://github.com/kevdoran/projector"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pj"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_darwin_amd64.tar.gz"
      sha256 "a2ca7e65218c59be7e6c70280ceec1eff1a1a888cbb945b5ba782a0ae1fbb4ff"
    end
    on_arm do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_darwin_arm64.tar.gz"
      sha256 "d66175d6314f85f5db6de03ef6b8e04b9bed3dc84f685dab9ed7135693ee1e2b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_linux_amd64.tar.gz"
      sha256 "a40439601de044aff2ad0ecc6d3bb24c7f7bf3ae5772fe074c6b263306b7a2e1"
    end
    on_arm do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_linux_arm64.tar.gz"
      sha256 "5ea94a2f1df264ad59382e13d3c7988b766e755bf19e63d6b055ebcf9f408fd3"
    end
  end

  # No zap stanza required
end
