# This file was generated by GoReleaser. DO NOT EDIT.
cask "pj" do
  name "pj"
  desc "Manage parallel projects backed by git worktrees"
  homepage "https://github.com/kevdoran/projector"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pj"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_darwin_amd64.tar.gz"
      sha256 "40c368213a69c40c7fb1879e901b7f9fa31871b48dbe67e9aed691b4dfbb4d70"
    end
    on_arm do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_darwin_arm64.tar.gz"
      sha256 "803887e9f104a70a9d6b1d9e6080186b811f2abebbb03d19e8d96986702b6756"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_linux_amd64.tar.gz"
      sha256 "b031be6c213b117dea7e7ea6e54124399c5bb763a27c93723892dcbc9ea6ff21"
    end
    on_arm do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_linux_arm64.tar.gz"
      sha256 "658f5d7070ce19584e9e095e001dcba4bc176ba987e3e58933c44da50557ff5e"
    end
  end

  # No zap stanza required
end
