# This file was generated by GoReleaser. DO NOT EDIT.
cask "pj" do
  name "pj"
  desc "Manage parallel projects backed by git worktrees"
  homepage "https://github.com/kevdoran/projector"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pj"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_darwin_amd64.tar.gz"
      sha256 "ae2f3176a1459c27be371e9ddb471748124270cb400839fa8db2a4e6b0b4e740"
    end
    on_arm do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_darwin_arm64.tar.gz"
      sha256 "dd8a33d24c2ad0e29d9cb99a611d37e67dabee255aa304e0c57dbcf5ad232106"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_linux_amd64.tar.gz"
      sha256 "f9ea9c594f0dc61b35d4b73b8c9de848dcddd0db09f02bdd996363fbc7bf0839"
    end
    on_arm do
      url "https://github.com/kevdoran/projector/releases/download/v#{version}/pj_linux_arm64.tar.gz"
      sha256 "6eee4d0805d6a2429eca35cfd11896afa7b6cbc7394c6cb6ec1ac39775e1d83b"
    end
  end

  # No zap stanza required
end
